### ISSUE TITLE
javadoc is wrong for some things

### ISSUE THREAD

**Issue by rhysdh540** [SamSah-Nixon/ExtremeCutthroatGoFish#1]
[here](https://github.com/SamSah-Nixon/ExtremeCutthroatGoFish/blob/master/Player.java#L120)
[here](https://github.com/SamSah-Nixon/ExtremeCutthroatGoFish/blob/master/Player.java#L39) (the and should be or)

**Comment by SamSah-Nixon** [comment]
You're Wrong, I'm right. Case Closed.

**Comment by rhysdh540** [comment]
No ur wrong

**Comment by rhysdh540** [comment]
Case opened

**Comment by SamSah-Nixon** [comment]
Proof? O_O
